apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux    
      containers:
        - name: metabase-staging
          image: metabase/metabase:latest
          ports:
            - containerPort: 3000
          env:
            - name: MB_DB_TYPE
              value: "postgres"
            - name: MB_DB_DBNAME
              value: "postgres"
            - name: MB_DB_PORT
              value: "5432"
            - name: MB_DB_USER
              value: "testuser"
            - name: MB_DB_PASS
              value: "supersecret"
            - name: MB_DB_HOST
              value: "postgres-proxy"