apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-proxy
  template:
    metadata:
      labels:
        app: postgres-proxy
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: netbird
        image: netbirdio/netbird:latest
        securityContext:
          privileged: true
        env:
        - name: NB_SETUP_KEY
          valueFrom:
            secretKeyRef:
              name: netbird-secret
              key: setup-key
        - name: NB_MANAGEMENT_URL
          value: "https://api.netbird.io"       # Or your self-hosted mgmt
        - name: NB_SIGNAL_URL
          value: "https://signal.netbird.io"    # Or your self-hosted signal
        - name: NB_HOSTNAME
          value: "postgres-proxy"
      - name: haproxy
        image: haproxy:latest
        ports:
        - containerPort: 5433
        volumeMounts:
        - name: haproxy-config
          mountPath: /usr/local/etc/haproxy
      volumes:
      - name: haproxy-config
        configMap:
          name: haproxy-config
