apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
      log stdout format raw local0

    defaults
      log global
      mode tcp
      timeout connect 10s
      timeout client  1h
      timeout server  1h

    frontend pgsql_frontend
      bind 0.0.0.0:5432
      default_backend pgsql_backend

    backend pgsql_backend
      balance roundrobin
      option tcp-check
      server db1 postgres-svc.default.svc.cluster.local:5432 check
